name: geotiff-to-mesh

channels:
  - conda-forge
  - defaults

dependencies:
  # Core dependencies
  - python=3.12
  - gdal=3.10.*
  - numpy=1.26.*
  - numpy-stl=3.2.*
  - tqdm=4.67.*
  - scipy=1.14.*

  # Development dependencies
  - black=24.10.*
  - pre-commit=4.0.*
