name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: geotiff-to-mesh
          environment-file: environment.yml
          auto-activate-base: false

      - name: Install 7zip
        run: sudo apt-get install -y p7zip-full

      - name: Extract sample data
        run: 7z x samples/Urupukapuka.7z -osamples/Urupukapuka

      - name: Run geotiff-to-mesh script
        shell: bash -l {0}
        run: |
          conda activate geotiff-to-mesh
          python geotiff-to-mesh.py samples/Urupukapuka output.stl

      - name: Verify output file exists
        run: |
          if [ ! -f output.stl ]; then
            echo "Error: output.stl was not created"
            exit 1
          fi
          echo "Success: output.stl was created"
